[window]
padding = { x = 0, y = 0 }
decorations = "none"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
bold_italic = { family = "JetBrainsMono Nerd Font" }

[colors]
primary = { background = "#000000", foreground = "#ffffff" }

[colors.normal]
black = "#ffffff"
white = "#ffffff"
red = "#ffffff"
green = "#ffffff"
yellow = "#ffffff"
blue = "#ffffff"
magenta = "#ffffff"
cyan = "#ffffff"

[colors.bright]
black = "#ffffff"
white = "#ffffff"
red = "#ffffff"
green = "#ffffff"
yellow = "#ffffff"
blue = "#ffffff"
magenta = "#ffffff"
cyan = "#ffffff"

[colors.dim]
black = "#ffffff"
white = "#ffffff"
red = "#ffffff"
green = "#ffffff"
yellow = "#ffffff"
blue = "#ffffff"
magenta = "#ffffff"
cyan = "#ffffff"
